package com.acme.edu;

public enum State {
    INIT_STATE,
    ARRAY_INPUT,
    BOOLEAN_INPUT,
    BYTE_INPUT,
    CHAR_INPUT,
    INT_INPUT,
    MULTIDIM_ARRAY_INPUT,
    OBJECT_INPUT,
    STRING_INPUT,
    TWODIM_ARRAY_INPUT,
    VARARGS_ARRAY_INPUT;
}
